{{- if ( and .Values.docker.secret.username .Values.docker.secret.password ) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "activegate.fullname" . }}-docker
data:
 .dockerconfigjson: {{ template "activegate.secret" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}