{{- if .Values.dumps.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "activegate.fullname" . }}-tls
  labels:
    app: {{ template "activegate.name" . }}
data:
  tls.crt: {{ .Values.dumps.tls.cert | b64enc }}
  tls.key: {{ .Values.dumps.tls.key | b64enc }}
type: kubernetes.io/tls
{{- end }}
