FROM cloudfoundry/cflinuxfs3

RUN mkdir -p /usr/share/man/man1 \
   && apt-get -qq update \
   && apt-get -qq upgrade \
   && apt-get -qq install openjdk-8-jdk

COPY artifacts/spring-music-1.0.jar /work/spring-music.jar
COPY scripts/startup.sh /work/startup.sh
COPY scripts/agent.sh /opt/dynatrace/sap/agent.sh

RUN chmod +x /opt/dynatrace/sap/agent.sh

ENTRYPOINT /work/startup.sh
